#!/usr/bin/env perl

use strict;
use warnings;

use lib map { "__FILE__/../" . $_ } qw(app/helpers app/controllers app/models lib);

use HTTP::Engine;


my $engine = HTTP::Engine->new(

    interface => {
        module => "ServerSimple",
        args   => {
            host => "localhost",
            port => "3500",
        },  
        request_handler => \&SimpleApp::handle_request, # still need set
    }
);

$engine->run();

