#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename;
use lib dirname(__FILE__) . "/../../../lib/";
use lib map { dirname(__FILE__) . "/../" . $_ } qw(app/helpers app/controllers app/models lib);

require "application_controller.pm";
# TODO: Load all module in application.

use HTTP::Engine;
my $engine = HTTP::Engine->new(

    interface => {
        module => "ServerSimple",
        args   => {
            host => "localhost",
            port => "3500",
        },  
        request_handler => \&SimpleApp::handle_request, # still need set
    }
);

$engine->run();

